language: node_js
node_js:
  - "16"
sudo: false
dist: trusty
script:
  - npm run eslint
  - npm run test -- --failTaskOnError
  - npm install # Work around bug in "npm shrinkwrap" which is used by create-zip.
  - npm run create-zip
